local beautiful = require("beautiful")
local vars = require("main.user-variables")
local theme_path = vars.theme_path
beautiful.init(theme_path)

require("bar.modules.spotifybox")
require("bar.modules.volumebox")
require("bar.modules.cpubox")
require("bar.modules.keyboardlayoutbox")
require("bar.modules.membox")
require("bar.modules.layoutbox-container")
require("bar.modules.systray")
require("bar.modules.datetimebox")
require("bar.modules.net")
require("bar.modules.playerctl")
require("bar.modules.launcherbox")
